export type Status='ALREADY_PUBLISHED'|'CANDIDATE_TO_PUBLISH'|'REVIEW_REQUIRED'|'POSSIBLE_DUPLICATE'|'INCOMPLETE_DATA'|'INVALID_SKU'|'INVALID_EAN'|'UNMATCHED_ML_LISTING';
export interface Product {ecomm_id?:string;sku?:string;sku_product?:string;sku_variant?:string;sku_effective?:string;ean?:string;brand?:string;name?:string;stock?:number;price?:number}
export interface Listing {external_id?:string;status?:string;sku?:string;title?:string;url?:string;inventory_linked?:string}
export interface Result {product?:Product;listing?:Listing;matched_listing_count:number;matched_listing_ids:string[];multiple_ml_listings:boolean;status:Status;reason:string;confidence:number;match_method:string;issues:{severity:string;message:string}[]}
export interface ImportDiagnostics {source:string;filename:string;rows_read:number;rows_accepted:number;rows_discarded:number;header_row:number;recognized_columns:Record<string,string>;ignored_columns:string[];warnings:string[];canonical_products?:number;grouped_rows?:number;associated_rows?:number;conflicts?:string[]}
export interface Summary {total_products:number;total_listings:number;total_ecomm_rows?:number;total_ecomm_associated_rows?:number;mercadolibre_source?:string;import_diagnostics?:ImportDiagnostics[];[key:string]:number|string|ImportDiagnostics[]|undefined}
export interface ImportJob {id:number;filename:string;source:string;started_at:string;records:number;processed:number;errors:number;status:string;unknown_columns:string[];diagnostics:ImportDiagnostics}
export interface MercadoLibreStatus {connected:boolean;user_id?:string;token_expiration?:string;token_expired:boolean;last_sync?:string;listing_count:number}
export type ReadinessStatus='READY_CORE_DATA'|'REVIEW_REQUIRED'|'BLOCKED'|'NO_STOCK'|'ALREADY_PUBLISHED';
export interface ReadinessItem {product:Product;reconciliation_status:Status;readiness_status:ReadinessStatus;reason_codes:string[];reasons:string[];issues:{severity:string;code?:string;message:string}[];matched_listing_ids:string[]}
export interface ReadinessReasonSummary {code:string;label:string;count:number}
export interface ReadinessReport {reconciliation_run_id:number;mercadolibre_source?:string;summary:{total_products:number;actionable_with_stock:number;READY_CORE_DATA:number;REVIEW_REQUIRED:number;BLOCKED:number;NO_STOCK:number;ALREADY_PUBLISHED:number};reason_summary:ReadinessReasonSummary[];pending_external_checks:string[];items:ReadinessItem[]}
export type EnrichmentResearchStatus='PENDING_RESEARCH';
export type EnrichmentNature='PACK_OR_KIT'|'BULK_OR_FRACTIONED'|'ARTISANAL'|'STANDARD_UNIT'|'AMBIGUOUS_GENERIC';
export type InternalEvidenceConfidence='HIGH'|'MEDIUM'|'NONE';
export interface EnrichmentProposal {ean?:string|null;brand?:string|null;source_name?:string|null;source_url?:string|null;confidence?:string|null;notes?:string|null}
export interface InternalCatalogEvidence {brand_candidate?:string|null;candidate_brands:string[];confidence:InternalEvidenceConfidence;method:string;reason:string;related_sku?:string|null;related_name?:string|null;related_ean?:string|null;similarity?:number|null}
export interface EnrichmentItem {product:Product;readiness_status:ReadinessStatus;reason_codes:string[];missing_fields:string[];research_status:EnrichmentResearchStatus;nature_code:EnrichmentNature;nature_label:string;nature_basis:string;research_strategy:string;internal_evidence:InternalCatalogEvidence;proposal:EnrichmentProposal}
export interface EnrichmentClassificationSummary {code:EnrichmentNature;label:string;count:number;strategy:string}
export interface EnrichmentInternalEvidenceSummary {high:number;medium:number;none:number;description:string}
export interface EnrichmentReport {reconciliation_run_id:number;mercadolibre_source?:string;summary:{total_eligible:number;missing_ean:number;missing_brand:number;missing_both:number;pilot_size:number;pilot_limit:number;internal_brand_candidates:number;internal_evidence_ambiguous:number;known_brands_in_catalog:number};classification_summary:EnrichmentClassificationSummary[];internal_evidence_summary:EnrichmentInternalEvidenceSummary;policy:{mode:string;description:string};items:EnrichmentItem[]}
export type EnrichmentReviewStatus='PENDING'|'APPROVED_PROPOSAL'|'REJECTED'|'EXTERNAL_RESEARCH';
export type EnrichmentPriority='P1_HIGH'|'P2_MEDIUM'|'P3_AMBIGUOUS'|'P4_EXTERNAL';
export interface EnrichmentReviewItem {product_key:string;product:Product;missing_fields:string[];nature_code:EnrichmentNature;nature_label:string;internal_evidence:InternalCatalogEvidence;priority_code:EnrichmentPriority;priority_label:string;review_status:EnrichmentReviewStatus;proposed_brand?:string|null;proposed_ean?:string|null;note?:string|null;updated_at?:string|null;history_count:number}
export interface EnrichmentReviewQueue {reconciliation_run_id:number;summary:{total_eligible:number;queue_total:number;internal_brand_candidates:number;internal_ambiguous:number;without_internal_evidence:number;PENDING:number;APPROVED_PROPOSAL:number;REJECTED:number;EXTERNAL_RESEARCH:number};priority_summary:{code:EnrichmentPriority;label:string;count:number}[];policy:{mode:string;description:string};items:EnrichmentReviewItem[]}
export type ExternalResearchStatus='DRAFT'|'READY_FOR_REVIEW'|'EVIDENCE_ACCEPTED'|'REJECTED';
export type ExternalResearchConfidence='LOW'|'MEDIUM'|'HIGH';
export interface ExternalResearchItem {product_key:string;product:Product;nature_label?:string;priority_code:EnrichmentPriority;internal_evidence:InternalCatalogEvidence;research_status:ExternalResearchStatus;proposed_brand?:string|null;proposed_ean?:string|null;source_name?:string|null;source_url?:string|null;confidence?:ExternalResearchConfidence|null;notes?:string|null;updated_at?:string|null;history_count:number}
export interface ExternalResearchQueue {summary:{total:number;DRAFT:number;READY_FOR_REVIEW:number;EVIDENCE_ACCEPTED:number;REJECTED:number};policy:{mode:string;description:string};items:ExternalResearchItem[]}
export interface ExternalResearchPayload {product_key:string;status:ExternalResearchStatus;proposed_brand?:string;proposed_ean?:string;source_name?:string;source_url?:string;confidence?:ExternalResearchConfidence;notes?:string}
export type PrepublicationCheckStatus='PASSED'|'WAITING_IMAGE_DATA'|'WAITING_ML_CONNECTION'|'READY_TO_VALIDATE'|'BLOCKED';
export interface PrepublicationVerifiedCore {brand?:string|null;ean?:string|null;source_name?:string|null;source_url?:string|null;confidence?:string|null}
export interface PrepublicationItem {product_key:string;product:Product;core_source:'ECOMM_CORE'|'ACCEPTED_EVIDENCE';core_source_label:string;verified_core_data:PrepublicationVerifiedCore;status:'WAITING_EXTERNAL_CONTROLS';checks:{core_data:PrepublicationCheckStatus;images:PrepublicationCheckStatus;category:PrepublicationCheckStatus;attributes:PrepublicationCheckStatus;preview:PrepublicationCheckStatus}}
export interface PrepublicationReport {summary:{total:number;from_ecomm_core:number;from_accepted_evidence:number;approved_images:number;waiting_images:number;waiting_ml_connection:number;ready_for_preview:number};mercadolibre_connected:boolean;pending_controls:string[];policy:{mode:string;description:string};items:PrepublicationItem[]}
export type ImageReviewStatus='DRAFT'|'READY_FOR_REVIEW'|'APPROVED'|'REJECTED';
export type ImageSourceType='OWN_ML'|'ML_CATALOG'|'MANUFACTURER'|'OTHER_SELLER'|'OTHER';
export type ImageMatchBasis='GTIN_EXACT'|'OWN_LISTING'|'MANUAL_EXACT';
export interface PrepublicationImageItem {product_key:string;product:Product;verified_core_data:PrepublicationVerifiedCore;image_status:ImageReviewStatus;source_type?:ImageSourceType|null;source_label?:string|null;source_name?:string|null;source_url?:string|null;image_urls:string[];match_basis?:ImageMatchBasis|null;exact_match:boolean;authorized_for_use:boolean;notes?:string|null;updated_at?:string|null;history_count:number}
export interface PrepublicationImageQueue {summary:{total:number;DRAFT:number;READY_FOR_REVIEW:number;APPROVED:number;REJECTED:number;approved:number;pending:number};mercadolibre_connected:boolean;source_policy:{code:ImageSourceType;label:string;approvable:boolean}[];policy:{mode:string;description:string;automatic_ml_search:'WAITING_CONNECTION'|'PENDING_IMPLEMENTATION'};items:PrepublicationImageItem[]}
export interface PrepublicationImagePayload {product_key:string;status:ImageReviewStatus;source_type?:ImageSourceType;source_name?:string;source_url?:string;image_urls:string[];match_basis?:ImageMatchBasis;exact_match:boolean;authorized_for_use:boolean;notes?:string}
