import {useEffect,useState} from 'react';
import {api} from '../services/api';
import type {MercadoLibreStatus,Summary} from '../types/catalog';

const cards=[['total_ecomm_rows','Filas Ecomm importadas'],['total_products','Productos Ecomm únicos'],['total_ecomm_associated_rows','Filas/publicaciones asociadas'],['total_listings','Publicaciones ML'],['ALREADY_PUBLISHED','Productos ya publicados'],['CANDIDATE_TO_PUBLISH','Candidatos'],['REVIEW_REQUIRED','Revisión'],['POSSIBLE_DUPLICATE','Posibles duplicados Ecomm'],['MULTIPLE_ML_LISTINGS','Productos con múltiples publicaciones ML']];
const emptyMl:MercadoLibreStatus={connected:false,token_expired:false,listing_count:0};
const date=(value?:string)=>value?new Date(value).toLocaleString('es-AR'):'Nunca';

export function Dashboard(){
  const [data,setData]=useState<Summary>({total_products:0,total_listings:0});
  const [ml,setMl]=useState<MercadoLibreStatus>(emptyMl);
  const [source,setSource]=useState('AUTO');
  const [busy,setBusy]=useState(false);
  const [syncing,setSyncing]=useState(false);
  const [message,setMessage]=useState('');
  const load=async()=>{const [summary,status]=await Promise.all([api.dashboard(),api.mlStatus()]);setData(summary);setMl(status)};
  useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
  async function analyze(){setBusy(true);setMessage('');try{await api.analyze(source);await load();setMessage('Análisis completado correctamente.')}catch(e){setMessage(e instanceof Error?e.message:'Error inesperado')}finally{setBusy(false)}}
  async function connect(){try{const {url}=await api.mlAuthUrl();window.location.assign(url)}catch(e){setMessage(e instanceof Error?e.message:'Error inesperado')}}
  async function sync(){setSyncing(true);setMessage('');try{const result=await api.mlSync();await load();setMessage(`Sincronización completada: ${result.listing_count} publicaciones.`)}catch(e){setMessage(e instanceof Error?e.message:'Error inesperado')}finally{setSyncing(false)}}
  const ecomm=data.import_diagnostics?.find(item=>item.source==='ECOMM_APP');
  return <><header><div><p className="eyebrow">CATALOG RECONCILER</p><h1>Resumen del catálogo</h1><p>Estado consolidado de Ecomm-App y Mercado Libre.</p></div><div className="analysis-actions"><label>Mercado Libre <select value={source} onChange={event=>setSource(event.target.value)}><option value="AUTO">Automático</option><option value="API">API</option><option value="XLSX">XLSX</option></select></label><button onClick={analyze} disabled={busy}>{busy?'Analizando…':'Analizar catálogo'}</button></div></header>{message&&<div className="notice">{message}</div>}
  <section className="panel connection"><div><p className="eyebrow">FUENTE ECOMM-APP · SOLO LECTURA</p><h2>{ecomm?'XLSX activo':'Sin importación'}</h2><div className="connection-details"><span>Fuente actual <strong>{ecomm?'XLSX':'—'}</strong></span><span>Archivo <strong>{ecomm?.filename||'—'}</strong></span><span>Filas aceptadas <strong>{ecomm?.rows_accepted??0}</strong></span><span>Productos canónicos <strong>{ecomm?.canonical_products??0}</strong></span><span>API <strong>Pendiente de confirmación</strong></span></div></div></section>
  <section className="panel connection"><div><p className="eyebrow">CONEXIÓN MERCADO LIBRE · ACCESO CONTROLADO</p><h2>{syncing?'Sincronizando…':!ml.connected?'No conectado':ml.token_expired?'Token vencido / requiere reconexión':'Conectado'}</h2><div className="connection-details"><span>Usuario <strong>{ml.user_id||'—'}</strong></span><span>Publicaciones obtenidas <strong>{ml.listing_count}</strong></span><span>Última sincronización <strong>{date(ml.last_sync)}</strong></span><span>Vencimiento del token <strong>{date(ml.token_expiration)}</strong></span></div></div><div>{(!ml.connected||ml.token_expired)&&<button onClick={connect}>Conectar Mercado Libre</button>} {ml.connected&&<><button onClick={connect}>Reconectar Mercado Libre</button> <button onClick={sync} disabled={syncing}>{syncing?'Sincronizando…':'Sincronizar Mercado Libre'}</button></>}</div></section>
  <p className="source-indicator">Fuente utilizada en la última reconciliación: <strong>{data.mercadolibre_source==='MERCADOLIBRE_API'?'API':data.mercadolibre_source==='MERCADOLIBRE'?'XLSX':'Sin análisis'}</strong></p>
  <section className="cards">{cards.map(([key,label])=><article key={key}><span>{label}</span><strong>{Number(data[key]||0).toLocaleString('es-AR')}</strong></article>)}</section><section className="panel"><h2>Diagnóstico de importación</h2>{data.import_diagnostics?.length?data.import_diagnostics.map(item=><div className="diagnostic" key={item.source}><h3>{item.source} <small>{item.filename}</small></h3><div className="diagnostic-counts"><span>Leídas <strong>{item.rows_read}</strong></span><span>Aceptadas <strong>{item.rows_accepted}</strong></span><span>Descartadas <strong>{item.rows_discarded}</strong></span><span>Encabezado <strong>fila {item.header_row}</strong></span>{item.canonical_products!==undefined&&<><span>Canónicos <strong>{item.canonical_products}</strong></span><span>Filas agrupadas <strong>{item.grouped_rows}</strong></span><span>Asociadas <strong>{item.associated_rows}</strong></span><span>Conflictos <strong>{item.conflicts?.length||0}</strong></span></>}</div><p><b>Reconocidas:</b> {Object.values(item.recognized_columns).join(', ')||'ninguna'}</p><p><b>Ignoradas:</b> {item.ignored_columns.join(', ')||'ninguna'}</p>{(item.warnings.length>0||(item.conflicts?.length||0)>0)&&<details className="notice"><summary><strong>Ver advertencias y conflictos ({item.warnings.length+(item.conflicts?.length||0)})</strong></summary><div>{item.warnings.map(warning=><p className="diagnostic-warning" key={warning}>⚠ {warning}</p>)}{item.conflicts?.map(conflict=><p className="diagnostic-warning" key={conflict}>⚠ {conflict}</p>)}</div></details>}</div>):<p>Todavía no hay importaciones para diagnosticar.</p>}</section><section className="panel"><h2>Flujo seguro</h2><p>KIKI Tech lee, sincroniza y usa validadores oficiales de Mercado Libre, pero no crea, edita ni elimina publicaciones automáticamente.</p></section></>}
